config/routes.rb
Rails.application.routes.draw do
  get 'surveys/thanks' => 'surveys#thanks', as: 'thanks'
  get 'surveys/:id' => 'surveys#show', as: 'survey'
  get 'results/:id.json' => 'surveys#survey_json', as: 'survey_json'
  match 'surveys/:id/token' => 'surveys#generate_token', as: 'generate_token', via: %w(get post)
  match 'surveys/:id/revoke' => 'surveys#revoke_tokens', via: %w(get post)
  post 'surveys/:id' => 'surveys#submit', as: 'survey_submit'

end

app/models/serializers/survey.rb
module Serializers
  class Survey < SimpleDelegator
    def as_json
      out = {
        id: survey_id,
        title: title,
        description: description,
        participants: participants
      }

      unless active?
        out[:questions] = questions.map {|q| Serializers::Question.new(q).as_json }
        out[:intersections] = intersections.map {|i| Serializers::Intersection.new(i).as_json }
      end

      out
    end
  end
end

app/models/survey.rb
# frozen_string_literal: true

# A record to represent a survey. This is not an ActiveRecord-based model, just
# a place to centralize the survey-loading, processing in an object.
class Survey
  include ActiveModel::Conversion

  SURVEY_META_KEY = '_survey'.freeze
  SURVEY_PARTICIPANTS = 'participants'.freeze

  # Needed to make Rails forms happy
  def model_name
    ActiveModel::Name.new(Survey)
  end

  def persisted?
    false
  end

  def initialize(arg)
    fail ActiveRecord::NotFound if arg.nil?

    hash = case arg
           when String
             YAML.load(File.open(Rails.root.join('config', 'surveys', "#{arg}.yml"))).merge('id' => arg)
           when Hash
             arg
           else
             fail 'Not implemented yet'
           end

    @hash = IceNine.deep_freeze(hash)

    validate_survey
  rescue Errno::ENOENT
    raise ActiveRecord::RecordNotFound, "Survey #{arg} not found"
  end

  def intro
    if @intro.nil?
      @intro = @hash['intro']

      # load a markdown file if specified
      if @intro =~ /\.md$/
        @intro = File.read(Rails.root.join('config', 'surveys', @intro))
      end
    end

    @intro
  end

  def title
    @hash['title']
  end

  def description
    @hash['description']
  end

  def active?
    !(@hash.key?('active') && @hash['active'] == false)
  end

  # Access params
  def access_params
    if @access_params.nil?
      @access_params = @hash['access'] || {'type' => 'token'}
    end

    @access_params
  end

  def revoke_all_tokens
    SurveyToken.revoke_all_for_survey(survey_id)
  end

  def survey_id
    @hash['id']
  end
  alias id survey_id

  def questions
    if @questions.nil?
      @questions = @hash['questions'].map {|h| Question.new(self, h) }
    end

    @questions
  end

  def valid_question_key?(key)
    questions.detect {|q| q.key == key } != nil
  end

  def [](key)
    questions.detect {|q| q.key == key }
  end

  def intersections
    if @intersections.nil?
      @intersections =
        if @hash['intersections'].nil?
          []
        else
          @hash['intersections'].map {|h| Intersection.new(self, h) }
        end
    end

    @intersections
  end

  def tally_for(field, value)
    Tally.tally_for(survey_id, field, value)
  end

  def tallies(field)
    Tally.where(survey_id: survey_id, field: field)
  end

  def count_participant
    Tally.record(survey_id, SURVEY_META_KEY, SURVEY_PARTICIPANTS)
  end

  def participants
    tally_for(SURVEY_META_KEY, SURVEY_PARTICIPANTS)
  end

  private

  def validate_survey
    fail 'You must include an id field in the survey' if survey_id.blank?
  end

  # def method_missing(method_sym, *arguments, &block)
  #   if @hash['questions'].any? {|h| h['key'] == method_sym.to_s }
  #     nil
  #   else
  #     super
  #   end
  # end
end

app/controllers/survey_controller.rb
# The only controller we need for handling the survey form for now
class SurveyController < ApplicationController
  before_filter :load_survey

  def new
  end

  def submit
    raise params.inspect
  end

  private

  def load_survey
    @survey = Survey.new
  end
end

app/controllers/surveys_controller.rb
# The only controller we need for handling the survey form for now
class SurveysController < ApplicationController
  before_action :load_survey, only: [:submit, :show, :results, :generate_token, :revoke_tokens]

  def show
    check_access_allowed!
    @hidden = access_control.hidden_form_variables(params)
    @md = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  def survey_json
    @survey = Survey.new(params[:id])
    render json: Serializers::Survey.new(@survey).as_json
  end

  def submit
    check_access_allowed!
    ResponseProcessor.new(params[:survey], @survey).perform
    revoke_access!
    redirect_to(action: :thanks)
  end

  def generate_token
    require_admin_auth!
    out = ''

    n = 1
    n = params[:n].to_i if params[:n]

    n.times.each do
      token = SurveyToken.generate(@survey.survey_id)
      out << survey_url(@survey.survey_id) + '?token=' + token + "\n"
    end

    render text: out, status: :ok
  end

  def revoke_tokens
    require_admin_auth!
    @survey.revoke_all_tokens
    render text: 'All tokens revoked', status: :ok
  end

  def thanks
  end

  private

  rescue_from ActionController::RoutingError, with: -> { render_404 }
  rescue_from ActiveRecord::RecordNotFound, with: -> { render_404 }
  rescue_from AccessException, with: -> { render_404 }

  def render_404
    return if status == 401 # for HTTP auth support
    respond_to do |format|
      format.html { render text: 'not found', status: 404 }
      format.all { render nothing: true, status: 404 }
    end
  end

  def load_survey
    @survey = Survey.new(params[:id])
    fail ActiveRecord::RecordNotFound unless @survey.active?
  end

  def access_params
    @access_params ||= @survey.access_params
  end

  def access_control
    if @access_control.nil?
      @access_control = case access_params['type']
                        when 'token'
                          TokenAccess.new(@survey.survey_id)
                        when 'http_auth'
                          HttpAuth.new(self, access_params)
                        else
                          fail AccessException, "Unrecognized access control type: #{access_params['type']}"
                        end
    end

    @access_control
  end

  def check_access_allowed!
    fail AccessException unless access_control.allowed?(params)
  end

  def revoke_access!
    access_control.revoke_for_user(params)
  end
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/surveys/_exclusive.html.erb
<div class="input">
  <%= label_tag "survey[#{question.key}]", question.text %>
  <ul class="usa-unstyled-list">
    <%- question.choices.each do |choice| %>
    <li class="radio">
      <%- option_id = "#{question.key}-#{choice.value}" %>
      <%= radio_button_tag "survey[#{question.key}]", choice.value, false, id: option_id %>
      <%= label_tag option_id, choice.label %>
    </li>
    <%- end %>
  </ul>
</div>

app/views/surveys/_freeform.html.erb
<div class="input">
  <%= label_tag "survey[#{question.key}]", question.text %>
  <%= text_field_tag "survey[#{question.key}]" %>
</div>

app/views/surveys/_multiple.html.erb
<div class="input">
  <%= label_tag question.key, question.text %>
  <ul class="usa-unstyled-list">
    <%- question.choices.each do |choice| %>
    <li class="radio">
      <%- option_id = "#{question.key}-#{choice.value}" %>
      <%= check_box_tag "survey[#{question.key}][]", choice.value, false, {id: option_id} %>
      <%= label_tag option_id, choice.label %>
    </li>
    <%- end %>
  </ul>
</div>

app/views/surveys/show.html.erb
<div class="survey">

  <header>
    <h1 class="usa-heading-alt"><%= @survey.title %></h1>
  </header>

  <div class="intro">
    <%= raw @md.render(@survey.intro) %>
  </div>

  <div class="usa-grid">
    <%= form_for @survey, url: survey_submit_path(@survey.id) do |form| %>
    <%- @hidden.each do |name, value| %>
      <%= hidden_field_tag name, value %>
    <%- end %>

    <%- @survey.questions.each do |question| %>
      <fieldset>
        <%- case question.question_type %>
          <%- when 'exclusive' %>
            <%= render partial: 'exclusive', locals: {form: form, question: question} %>
          <%- when 'multiple', 'exclusive-combo' %>
            <%= render partial: 'multiple', locals: {form: form, question: question} %>
          <%- when 'freeform' %>
            <%= render partial: 'freeform', locals: {form: form, question: question} %>
         <%- end %>

        <%- unless question.description.blank? %>
          <div class="description">
            <%= raw @md.render(question.description) %>
          </div>
        <%- end %>
      </fieldset>
    <%- end %>

      <%= form.submit 'Submit Response' %>
    <%- end %>
  </div>
</div>

app/views/surveys/thanks.html.erb
<h1>Thank You</h1>

<p>Thank you for participating in this survey</p>